steps:
  # Build the Docker image for the backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/${_GCP_PROJECT_ID}/${_REPO_NAME}/${_REPO_NAME}:$SHORT_SHA', '.']
    dir: '.'

  # Push the Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${_GCP_PROJECT_ID}/${_REPO_NAME}/${_REPO_NAME}:$SHORT_SHA']

  # Deploy the image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'us-central1-docker.pkg.dev/${_GCP_PROJECT_ID}/${_REPO_NAME}/${_REPO_NAME}:$SHORT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--add-cloudsql-instances'
      - '${_CLOUD_SQL_CONNECTION_NAME}'
      - '--set-env-vars'
      - >-
        CLOUD_SQL_CONNECTION_NAME=${_CLOUD_SQL_CONNECTION_NAME},
        DB_USER=${_DB_USER},
        DB_NAME=${_DB_NAME},
        # Note: $$ syntax references secret environment variables defined in secretEnv
        DB_PASS=$$DB_PASS,
        SESSION_SECRET=$$SESSION_SECRET
    secretEnv: ['DB_PASS', 'SESSION_SECRET']

  # Notify Slack
  - name: 'curlimages/curl:8.0.1'
    entrypoint: 'sh'
    args:
      - -c
      - |
        # Note: $$ syntax references secret environment variables defined in secretEnv
        curl -X POST -H 'Content-type: application/json' \
        --data "{\"text\":\"✅ Backend deployed to Cloud Run. Commit: $COMMIT_SHA\"}" \
        "$$SLACK_WEBHOOK_URL"
    secretEnv: ['SLACK_WEBHOOK_URL']

availableSecrets:
  secretManager:
    - versionName: projects/${_GCP_PROJECT_ID}/secrets/DB_PASS/versions/latest
      env: DB_PASS
    - versionName: projects/${_GCP_PROJECT_ID}/secrets/SESSION_SECRET/versions/latest
      env: SESSION_SECRET
    - versionName: projects/${_GCP_PROJECT_ID}/secrets/SLACK_WEBHOOK_URL/versions/latest
      env: SLACK_WEBHOOK_URL

substitutions:
  _GCP_PROJECT_ID: 'noted-reef-387021'
  _REPO_NAME: 'cloud-run-source-deploy'
  _SERVICE_NAME: 'mickeyf-org'
  _REGION: 'us-central1'
  _CLOUD_SQL_CONNECTION_NAME: 'noted-reef-387021:us-central1:cms-mickeyf'
  _DB_USER: 'cms_mickeyf'
  _DB_NAME: 'cms'

options:
  logging: CLOUD_LOGGING_ONLY
